Repository MIT-Emerging-Talent/ET6-foundations-group-25, pull requests merged in 2025-01, with the labels that each got.

#13 Done challenge "longest substring" #6
  solutions/longest_substring.py
  solutions/tests/test_longest_substring.py
Labels: Challenge

#17 Is-leap-year-chall-PR
  solutions/is_leap_year.py
  solutions/tests/test_is_leap_year.py
Labels: Challenge

#33 fix config error #Evan
  .vscode/settings.json
Labels: enhancement

#30 Done communication file
  collaboration/communication.md
Labels: documentation

#35 Multiplication table PR
  solutions/multiplication_table.py
  solutions/tests/test_multiplication_table.py
Labels: Solution

#38 completed prime numbers challenge
  solutions/prime_numbers.py
  solutions/tests/test_prime_numbers.py
Labels: Solution

#37 Count capitalized words
  solutions/count_capitalized_words.py
  solutions/tests/test_count_capitalized_words.py
Labels: Solution

#42 clarify "no function calls" item #Evan
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#39 completed missing number challenge
  solutions/missing_number.py
  solutions/tests/test_missing_number.py
Labels: Solution

#19 is-palindrome-ch-PR
  solutions/is_palindrome.py
  solutions/tests/test_is_palindrome.py
Labels: Solution

#44 Done missing numbers challenge and its test file
  solutions/missing_numbers.py
  solutions/tests/test_missing_numbers.py
Labels: Challenge

#47 Revert "Done missing numbers challenge and its test file"
  solutions/missing_numbers.py
  solutions/tests/test_missing_numbers.py
Labels: bug

#48 checklist updates post-Q&A #Evan
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#50 The Max integer Challenge
  solutions/max_integer.py
  solutions/tests/test_max_integer.py
Labels: Challenge

#57 Fix formatting issues caused by an update
  solutions/is_leap_year.py
Labels: bug

#59 Done missing numbers challenge and its test file
  solutions/missing_numbers2.py
  solutions/tests/test_missing_numbers2.py
Labels: Challenge

#53 Min integer Challenge
  collaboration/learning_goals.md
  solutions/min_integer.py
  solutions/tests/test_min_integer.py
Labels: enhancement

#66 completed the retrospective file
  collaboration/retrospective.md
Labels: documentation

#63 upload maximum_length.py challenge
  solutions/maximum_length.py
  solutions/tests/test_maximum_length.py
Labels: Challenge

#65 Done least common multiple challenge and its test file
  solutions/least_common_multiple.py
  solutions/tests/test_least_common_multiple.py
Labels: Challenge
